[theme]
background = "#1f1f28"
foreground = "#dcd7ba"
cursor = "#ff5d62"
selection = "#223249"

[theme.file]
normal = "#dcd7ba"
directory = "#7fb4ca"
executable = "#98bb6c"
symlink = "#c0a36e"

[theme.size]
small = "#98bb6c"
medium = "#ffa066"
large = "#e46876"

[theme.age]
new = "#7fb4ca"
old = "#957fb8"

[theme.git]
added = "#98bb6c"
modified = "#ffa066"
deleted = "#e46876"
renamed = "#7e9cd8"
untracked = "#c0a36e"

[theme.ui]
status_bar = "#1f1f28"
status_bar_text = "#a3d4d5"
border = "#54546d"
progress_bar = "#7e9cd8"
progress_bar_background = "#1f1f28"

